# Copyright FUJITSU LIMITED 2015-2017.

- name: copy default conf
  command: cp -pr conf orig.conf
  args:
    chdir: /opt/nginx-{{ nginx_version }}
    creates: /opt/nginx-{{ nginx_version }}/orig.conf

- name: Create /opt/nginx symlink
  file: state=link src=/opt/nginx-{{ nginx_version }} dest=/opt/nginx

- name: Deploy /etc/sysconfig/nginx
  copy: src=./resource/web/etc/sysconfig/nginx dest=/etc/sysconfig/nginx owner=root group=root mode=0644

- name: Deploy /opt/nginx/conf
  copy: src=./resource/web/opt/nginx/conf dest=/opt/nginx owner=root group=root

- name: Deploy /opt/nginx/conf/backend.conf
  template: src=./resource/web/opt/nginx/conf/backend.conf.j2 dest=/opt/nginx/conf/backend.conf owner=root group=root

- name: Deploy /etc/logrotate.d/nginx
  copy: src=./resource/web/etc/logrotate.d/nginx dest=/etc/logrotate.d/nginx owner=root group=root mode=0644

- name: Deploy /etc/systemd/system/nginx.service
  template: src=./resource/web/etc/systemd/system/nginx.service dest=/etc/systemd/system/nginx.service owner=root group=root mode=0755

- name: systemd reload
  command: systemctl daemon-reload

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
