# Copyright FUJITSU LIMITED 2015-2017.

- name: Deploy /etc/logrotate.d/memcached
  template: src=./resource/nfs/etc/logrotate.d/memcached dest=/etc/logrotate.d/memcached owner=root group=root mode=0644

- name: Deploy /etc/sysconfig/memcached_lock
  template: src=./resource/nfs/etc/sysconfig/memcached_lock.j2 dest=/etc/sysconfig/memcached_lock owner=root group=root mode=0644

- name: Deploy /etc/sysconfig/memcached_cache
  template: src=./resource/nfs/etc/sysconfig/memcached_cache.j2 dest=/etc/sysconfig/memcached_cache owner=root group=root mode=0644

- name: Deploy /etc/systemd/system/memcached_lock.service
  template: src=./resource/nfs/etc/systemd/system/memcached_lock.service dest=/etc/systemd/system/memcached_lock.service owner=root group=root mode=0755

- name: Deploy /etc/systemd/system/memcached_cache.service
  template: src=./resource/nfs/etc/systemd/system/memcached_cache.service dest=/etc/systemd/system/memcached_cache.service owner=root group=root mode=0755

- name: systemd reload
  command: systemctl daemon-reload

- name: Start memcached_lock
  systemd:
    name: memcached_lock
    state: started
    enabled: yes

- name: Start memcached_cache
  systemd:
    name: memcached_cache
    state: started
    enabled: yes
