# Copyright FUJITSU LIMITED 2015-2017.

- name: Create /personium directory
  file: state=directory path=/personium owner=root group=root mode=0755

- name: Create /personium/elasticsearch-{{ version }} directory
  file: "state=directory path=/personium/elasticsearch-{{ version }} owner=elasticsearch group=elasticsearch recurse=yes"

- name: Create log directory
  file: "state=directory path=/personium/elasticsearch-{{ version }}/log owner=elasticsearch group=elasticsearch recurse=yes"

- name: Create data directory
  file: "state=directory path=/personium/elasticsearch-{{ version }}/data owner=elasticsearch group=elasticsearch recurse=yes"

- name: Create work directory
  file: "state=directory path=/personium/elasticsearch-{{ version }}/work owner=elasticsearch group=elasticsearch recurse=yes"

- name: Create PID directory
  file: "state=directory path=/run/elasticsearch-{{ version }}/ owner=elasticsearch group=elasticsearch recurse=yes"

- name: Create symlink /personium/elasticsearch
  file: "state=link src=/personium/elasticsearch-{{ version }} dest=/personium/elasticsearch owner=elasticsearch group=elasticsearch"
