# Copyright FUJITSU LIMITED 2015-2017.

- name: download apache-maven-3.3.9-bin.zip
  get_url: url=http://ftp.yz.yamagata-u.ac.jp/pub/network/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip dest=/tmp mode=0440

- name: expand apache-maven-3.3.9-bin.zip
  unarchive: src=/tmp/apache-maven-3.3.9-bin.zip dest=/opt copy=no
