# Copyright FUJITSU LIMITED 2017.

- name: disable IPv6
  copy: src=./resource/common/etc/sysctl.d/disable_ipv6.conf dest=/etc/sysctl.d/disable_ipv6.conf owner=root group=root mode=0644

- name: Reflect setting
  command: sysctl -p/etc/sysctl.d/disable_ipv6.conf
