# Copyright FUJITSU LIMITED 2015-2017.

- name: check partition
  command: /sbin/parted -s /dev/{{ diskname }} print
  register: parted_print
  failed_when: parted_print.rc is not defined

- name: Secure partitions
  command: /sbin/parted -s /dev/{{ diskname }} mklabel gpt
  when: '"unknown" in parted_print.stdout'

- command: /sbin/parted -s /dev/{{ diskname }} 'mkpart primary xfs 1mb -1'
  when: '"unknown" in parted_print.stdout'

- name: Create /dev/{{ diskname }} filesystem
  filesystem: fstype=xfs dev=/dev/{{ diskname }}

- name: Check disk label
  command: xfs_admin -l /dev/{{ diskname }}
  register: disk_label

- name: Create label
  command: xfs_admin -L "{{ disklabel }}" /dev/{{ diskname }}
  when: '"{{ disklabel }}" not in disk_label.stdout'

- name: Mount disk
  mount: name={{ mountpoint }} src='LABEL={{ disklabel }}' fstype=xfs state=mounted
