# Copyright FUJITSU LIMITED 2015-2017.

- name: Create /personium/personium-esgclog directory
  file: "state=directory path=/personium/personium-esgclog owner=root group=root"

- name: Deploy /etc/systemd/system/esgclog.service
  copy: src=./resource/es/etc/systemd/system/esgclog.service dest=/etc/systemd/system/esgclog.service owner=root group=root mode=644

- name: Deploy /personium/personium-esgclog/printFullGC.awk
  copy: src=./resource/es/personium/personium-esgclog/printFullGC.awk dest=/personium/personium-esgclog/printFullGC.awk owner=root group=root mode=744

- name: Deploy /personium/personium-esgclog/esGCLog.sh
  copy: src=./resource/es/personium/personium-esgclog/esGCLog.sh dest=/personium/personium-esgclog/esGCLog.sh owner=root group=root mode=744

- name: Deploy /etc/logrotate.d/es-fullgc
  copy: src=./resource/es/etc/logrotate.d/es-fullgc dest=/etc/logrotate.d/es-fullgc owner=root group=root mode=0644

- name: systemd reload
  command: systemctl daemon-reload

- name: Start esgclog
  systemd:
    name: esgclog
    state: started
    enabled: yes
