# Copyright FUJITSU LIMITED 2015-2017.

- name: build module
  command: /opt/apache-maven-3.3.9/bin/mvn package -Dmaven.test.skip=true
  args:
    chdir: /tmp/personium-{{ build_mod }}
    creates: /root/ansible/resource/ap/opt/tomcat/webapps/personium-{{ release_mod }}.war
  environment:
    JAVA_HOME: /opt/jdk

- name: move module
  command: mv /tmp/personium-{{ build_mod }}/target/personium-{{ release_mod }}.war /root/ansible/resource/ap/opt/tomcat/webapps/personium-{{ release_mod }}.war
  args:
    creates: /root/ansible/resource/ap/opt/tomcat/webapps/personium-{{ release_mod }}.war
