# Copyright FUJITSU LIMITED 2015-2017.

- name: Install NFS Server
  yum: pkg={{ item }}
       state=present
  with_items:
    - nfs-utils

- name: Create directory
  file: path=/opt/nfs_webdav/
        mode=0755
        state=directory

- name: Update /etc/exports
  template: src=./resource/nfs/etc/exports dest=/etc/exports owner=root group=root mode=0644

- name: Update /etc/sysconfig/nfs
  template: src=./resource/nfs/etc/sysconfig/nfs dest=/etc/sysconfig/nfs owner=root group=root mode=0644

- name: In the /etc/fstab last line, list the mount destination server, directory and client side mount point.
  lineinfile: >
    dest=/etc/fstab
    line='personium-nfs:/opt/nfs_webdav /opt/nfs1 nfs nfsvers=3,tcp,hard,intr,sync,noac,lookupcache=none,bg'

- name: Update exports
  shell: exportfs -a

- name: start rpcbind
  systemd:
    name: rpcbind
    state: started
    enabled: yes

- name: start nfs
  systemd:
    name: nfs
    state: started
    enabled: yes

- name: start nfslock
  systemd:
    name: nfslock
    state: started
    enabled: yes
