# Copyright FUJITSU LIMITED 2015-2017.

- name: Get secret16
  command: cat /personium/personium-core/conf/token.key
  register: secret16

- name: Get salt
  command: cat /personium/personium-core/conf/salt.key
  register: salt

- name: clear master token
  set_fact: master_token=""

- name: Deploy personium-unit-config.properties
  template: src=./resource/ap/personium/personium-core/conf/18888/personium-unit-config.properties.j2 dest=/personium/personium-core/conf/18888/personium-unit-config.properties owner=root group=root mode=0644

#- name: Restart tomcat
#  systemd: name=tomcat state=restarted
#    when: enable_mastertoken == "false"

- name: Stop tomcat
  systemd: name=tomcat state=stopped

- name: Start tomcat
  poll: 5
  async: 60
  command: systemctl start tomcat &
  ignore_errors: True
