# Copyright FUJITSU LIMITED 2015.

- name: personium-engine/extensions の配備
  copy: src=./resource/ap/personium/18888/personium-engine/extensions dest=/personium/18888/personium-engine owner=personium group=personium mode=644

- name: secret16の採取
  command: cat /personium/personium-core/conf/token.key
  register: secret16

- name: saltの採取
  command: cat /personium/personium-core/conf/salt.key
  register: salt

- name: personium-config.properties の配備
  template: src=./resource/ap/personium/personium-core/conf/18888/personium-unit-config.properties.j2 dest=/personium/personium-core/conf/18888/personium-unit-config.properties owner=root group=root mode=0644

- name: logback.xml の配備
  copy: src=./resource/ap/opt/logback/logback.xml dest=/opt/logback/logback.xml owner=personium group=personium mode=0644

- name: tomcat サービスの停止
  service: name=tomcat state=stopped

- name: /opt/tomcat/webapps/personium-core を削除する
  file: state=absent path=/opt/tomcat/webapps/personium-core

- name: /opt/tomcat/webapps/personium-engine を削除する
  file: state=absent path=/opt/tomcat/webapps/personium-engine

- name: personium-core.war の配備
  copy: src=./resource/ap/opt/tomcat/webapps/personium-core.war dest=/opt/tomcat/webapps/personium-core.war owner=personium group=personium mode=644

- name: personium-engine.war の配備
  copy: src=./resource/ap/opt/tomcat/webapps/personium-engine.war dest=/opt/tomcat/webapps/personium-engine.war owner=personium group=personium mode=644

- name: personium-custom-errorpage.jar の配備
  copy: src=./resource/ap/opt/tomcat/lib/personium-custom-errorpage.jar dest=/opt/tomcat/lib/personium-custom-errorpage.jar owner=root group=root mode=644

- name: tomcat サービスの起動
  service: name=tomcat state=started
