# Copyright FUJITSU LIMITED 2015-2017.

- name: Create group
  group: name={{ groupname }} gid={{ gid }} state=present

- name: Create user
  user: name={{ username }} uid={{ uid }} shell=/bin/bash group={{ groupname }} home=/opt/var/lib/{{ username }} comment="{{ comment }}" createhome=no

- name: Create /opt/var/lib directory
  file: "state=directory path=/opt/var/lib owner=root group=root"

- name: Create Home directory
  file: "state=directory path=/opt/var/lib/{{ username }} owner={{ username }} group={{ groupname }} recurse=yes"
