# Copyright FUJITSU LIMITED 2015-2022.

- name: Download JDK
  ansible.builtin.get_url:
    url: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4.1%2B1/OpenJDK17U-jdk_x64_linux_hotspot_17.0.4.1_1.tar.gz
    dest: /usr/src/jdk-17.0.4.1+1.tar.gz
    mode: 0660

- name: Expand JDK
  ansible.builtin.unarchive:
    src: /usr/src/jdk-17.0.4.1+1.tar.gz
    dest: /usr/src
    remote_src: true

- name: Change owner JDK
  file: "state=directory path=/usr/src/jdk-17.0.4.1+1 owner=root group=root recurse=yes"

- name: Deploy JDK
  command: "mv /usr/src/jdk-17.0.4.1+1 /opt creates=/opt/jdk-17.0.4.1+1"

- name: Create smlink /opt/jdk
  file: "state=link src=/opt/jdk-17.0.4.1+1 dest=/opt/jdk"

- name: Add JDK to environment variable
  copy: src=./resource/common/etc/bashrc dest=/etc/bashrc owner=root group=root mode=0644
