# Copyright FUJITSU LIMITED 2015-2019.

- name: Download JDK
  command: 'wget -q -O /usr/src/jdk8u192-b12.tar.gz https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12/OpenJDK8U-jdk_x64_linux_hotspot_8u192b12.tar.gz creates=/usr/src/jdk8u192-b12.tar.gz'

- name: Expand JDK
  command: "tar -xzf /usr/src/jdk8u192-b12.tar.gz -C /usr/src creates=/usr/src/jdk8u192-b12"

- name: Change owner JDK
  file: "state=directory path=/usr/src/jdk8u192-b12 owner=root group=root recurse=yes"

- name: Deploy JDK
  command: "mv /usr/src/jdk8u192-b12 /opt creates=/opt/jdk8u192-b12"

- name: Create smlink /opt/jdk
  file: "state=link src=/opt/jdk8u192-b12 dest=/opt/jdk"

- name: Add JDK to environment variable
  copy: src=./resource/common/etc/bashrc dest=/etc/bashrc owner=root group=root mode=0644
